name: Update Contributors Leaderboard

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Contributors
        uses: jakejarvis/github-contributors-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          readme_path: README.md
          contributors_per_line: 5
